const VALIDATION_CODE = 201;
const VALIDATION_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;
const SECRET = 'some-secret-key';
const NODE_PRODUCTION = 'production';

module.exports = {
  VALIDATION_CODE,
  VALIDATION_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  SECRET,
  NODE_PRODUCTION,
  JWT_SECRET: process.env.JWT_SECRET,
};
